version: "3.5"

services:
  web:
    image: tiangolo/uwsgi-nginx-flask:latest
    volumes:
      - ./app:/app
      - ${FLAGPATH}:/flag
    ports:
      - "${PORT}:80"


networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET}
